"""initial schema: documents, parent_chunks, tenants, eval_logs

Revision ID: 16576f3fe244
Revises: 
Create Date: 2026-04-27 22:06:25.396656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16576f3fe244'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('doc_type', sa.String(length=64), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('source_date', sa.Date(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_index(op.f('ix_documents_is_active'), 'documents', ['is_active'], unique=False)
    op.create_index(op.f('ix_documents_tenant_id'), 'documents', ['tenant_id'], unique=False)
    op.create_table('eval_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trace_id', sa.String(length=128), nullable=True),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('faithfulness', sa.Float(), nullable=True),
    sa.Column('answer_relevancy', sa.Float(), nullable=True),
    sa.Column('context_precision', sa.Float(), nullable=True),
    sa.Column('context_recall', sa.Float(), nullable=True),
    sa.Column('context_score', sa.Float(), nullable=True),
    sa.Column('user_feedback', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_logs_created_at'), 'eval_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_eval_logs_tenant_id'), 'eval_logs', ['tenant_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('qdrant_collection', sa.String(length=255), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.create_table('parent_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.String(length=128), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('page_num', sa.Integer(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parent_chunks_is_active'), 'parent_chunks', ['is_active'], unique=False)
    op.create_index(op.f('ix_parent_chunks_parent_id'), 'parent_chunks', ['parent_id'], unique=False)
    op.create_index('ix_parent_chunks_tenant_active', 'parent_chunks', ['tenant_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_parent_chunks_tenant_id'), 'parent_chunks', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parent_chunks_tenant_id'), table_name='parent_chunks')
    op.drop_index('ix_parent_chunks_tenant_active', table_name='parent_chunks')
    op.drop_index(op.f('ix_parent_chunks_parent_id'), table_name='parent_chunks')
    op.drop_index(op.f('ix_parent_chunks_is_active'), table_name='parent_chunks')
    op.drop_table('parent_chunks')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_eval_logs_tenant_id'), table_name='eval_logs')
    op.drop_index(op.f('ix_eval_logs_created_at'), table_name='eval_logs')
    op.drop_table('eval_logs')
    op.drop_index(op.f('ix_documents_tenant_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_is_active'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
